-- SQL script to create the 'alert' table in the database
-- if it does not already exist. This table will store
-- information about alerts generated by the system, including
-- timestamps, device IP addresses, alert types, messages,
-- severity levels, and acknowledgment status. The alert types
-- are categorized as 'NEW_DEVICE', 'ANOMALY', and 'MALICIOUS_URL'.
CREATE table if not exists alert (
ID integer PRIMARY KEY AUTOINCREMENT,
timestamp text not null,
device_ip text not null,
alert_type text CHECK(alert_type IN ('NEW_DEVICE', 'ANOMALY', 'MALICIOUS_URL')),
message text not null,
severity text not null CHECK(severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
acknowledged integer not null 
);