-- SQL script to create the 'alert' table in the database
-- if it does not already exist. This table will store
-- information about alerts generated by the system, including
-- timestamps, device IP addresses, alert types, messages,
-- severity levels, and acknowledgment status. The alert types
-- are categorized as 'NEW_DEVICE', 'ANOMALY', and 'MALICIOUS_URL'.
-- CREATE table if not exists alert (
-- ID integer PRIMARY KEY AUTOINCREMENT,
-- timestamp text not null,
-- device_ip text not null,
-- alert_type text CHECK(alert_type IN ('NEW_DEVICE', 'ANOMALY', 'MALICIOUS_URL')),
-- message text not null,
-- severity text not null CHECK(severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
-- acknowledged integer not null 
-- );
CREATE TABLE IF NOT EXISTS alerts (
id INTEGER PRIMARY KEY AUTOINCREMENT,
occurred_at TEXT NOT NULL,
device_id INTEGER,
alert_type TEXT CHECK(alert_type IN ('NEW_DEVICE','ANOMALY','MALICIOUS_URL')) NOT NULL,
message TEXT NOT NULL,
severity TEXT NOT NULL DEFAULT 'LOW' CHECK(severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
acknowledged INTEGER NOT NULL DEFAULT 0 CHECK(acknowledged IN (0,1)),
created_at TEXT NOT NULL DEFAULT (datetime('now')),
updated_at TEXT NOT NULL DEFAULT (datetime('now')),
FOREIGN KEY(device_id) REFERENCES devices(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_alerts_device ON alerts(device_id);